# Generated by Django 3.0.8 on 2021-04-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0003_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='is_fav',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
