# Generated by Django 3.0.8 on 2021-04-22 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0004_auto_20210422_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songs',
            old_name='is_fav',
            new_name='is_favourite',
        ),
    ]
