# Generated by Django 3.0.8 on 2021-04-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0009_auto_20210426_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
