# Generated by Django 3.0.8 on 2021-04-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeethUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneno', models.IntegerField(null=True)),
                ('profile_pic', models.ImageField(blank=True, default='img.png', null=True, upload_to='')),
            ],
        ),
    ]
