# Generated by Django 3.1.7 on 2021-04-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('image_link', models.CharField(max_length=400)),
            ],
        ),
    ]
