# Generated by Django 3.2 on 2021-04-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='singer',
            field=models.CharField(default='ram', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songs',
            name='year',
            field=models.IntegerField(default=1997),
            preserve_default=False,
        ),
    ]
