# Generated by Django 3.1.7 on 2021-04-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_geethusers_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeethUsers',
        ),
    ]
