# Generated by Django 3.2 on 2021-04-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0003_auto_20210417_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='phoneno',
            field=models.IntegerField(null=True),
        ),
    ]
