# Generated by Django 3.1.7 on 2021-04-20 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0003_delete_geethusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeethUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phoneno', models.IntegerField(null=True)),
                ('auth_token', models.CharField(max_length=100)),
                ('reset_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(blank=True, default='img.png', null=True, upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
