# Generated by Django 3.2 on 2021-04-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0004_geethusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geethusers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
