# Generated by Django 3.2 on 2021-04-17 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('musicapp', '0004_alter_users_phoneno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='GeethUsers',
        ),
    ]
