# Generated by Django 3.0.8 on 2021-04-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_alter_geethusers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geethusers',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
