# Generated by Django 3.2 on 2021-04-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0008_auto_20210419_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(max_length=200),
        ),
    ]
