# Generated by Django 3.0.8 on 2021-04-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('song_name', models.CharField(max_length=100)),
                ('album_image_link', models.FileField(upload_to='./Album_Images')),
                ('upload_file', models.FileField(upload_to='./Songs')),
                ('year', models.IntegerField()),
                ('singer', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
